version : '3'

services: 
    dthmysql:
        image:  mysql:8.0.2
        enironment:
            MYSQL_ROOT_PASSWORD: Singh.12345
            MYSQL_DATABASE: dth
        ports:
           -"3308:3306"
        
    dthimage:
        image:    sarbjot012/dthservice:latest
        ports:
          -8080:8080
        depends_on:
          -dthmysql
        
                