version : '2'

services:
    dthsql:
        image:  mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: August2September
            MYSQL_DATABASE: dth
        ports:
           - "3306:3306"

    dthimage:
        image: sarbjot012/dthservice:latest
        ports:
          - "8080:8080"
        depends_on:
                - "dthsql"
        environment:
                - SPRING_DATASOURCE_URL=jdbc:mysql://dthsql:3306/dth?useSSL=false&allowPublicKeyRetrieval=true;connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
        links:
                - dthsql:dthsql