version : '2'

services:
    dthsql:
        image:  mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: August2September
            MYSQL_DATABASE: dth
        ports:
           - 3306:3306

    dthimage:
         image: sarbjot012/dthservice:latest
         ports:
          - 8080:8080
         #volumes:
            #    - ./target/dthService-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/dth.war
            #    - ./target:/usr/local/tomcat/webapps
         depends_on:
            - dthsql
         environment:
            -  SPRING_DATASOURCE_URL=jdbc:mysql://dthsql:3306/dth?useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=0&socketTimeout=0&autoReconnect=true
            -  SPRING_PROFILES_ACTIVE=test
         links:
            -  dthsql:dthsql
