pipeline{
	agent any

    stages {
    	try {
	        stage ('Clone') {
	        	checkout scm
	        }
	        
	        stage('Build') {
	            steps {
	            	sh 'mvn' 'clean' 'install' '-DskipTests'
	            }
	        }
	        
	        stage('Test') {
	            steps {
	               	sh 'make check || true' 
	                junit '**/target/*.xml' 
	            }
	        }
	        
	        stage('Deploy') {
	            when {
	              expression {
	                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
	              }
	            }
	            steps {
	            	sh 'cd dth'
	                sh 'docker-compose up'
	            }
	        }
	     }catch (error){
		     currentBuild.result= 'FAILED'
		     throw err
	     }
    }
}