CREATE DEFINER=`root`@`localhost` PROCEDURE `create_Cutomer`()
BEGIN
		DROP TABLE IF EXISTS CUSTOMER;

		CREATE TABLE CUSTOMER (
			SUBSCRIBER_ID BIGINT PRIMARY KEY,
			REGISTERED_MOBILE BIGINT ,
			FIRST_NAME VARCHAR(30), 
			LAST_NAME VARCHAR(30)
		);
END