CREATE DEFINER=`root`@`localhost` PROCEDURE `createChannels`()
BEGIN

	DROP TABLE IF EXISTS CHANNELS;
	create table CHANNELS(
		CHANNEL_ID INT PRIMARY KEY,
		CHANNEL_NAME VARCHAR(20),
		COST_PER_MONTH DECIMAL
	);

END