FROM openjdk:8-jdk-alpine
VOLUME /app
COPY dthService-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/dth.war
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/usr/local/tomcat/webapps/dth.war"]